# Do use it only for development / testing purpose
version: "3.3"
services:

  compiler:
    build: ../..
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - compiler:/compiler
    ports:
      - 8082:8082
      - 9092:9092
    environment:
      DELETE_DOCKER_IMAGE: 'true'
      EXECUTION_MEMORY_MAX: 10000
      EXECUTION_MEMORY_MIN: 1
      EXECUTION_TIME_MAX: 15
      EXECUTION_TIME_MIN: 1
      MAX_REQUESTS: 10
      MAX_EXECUTION_CPUS: 0.2
      COMPILATION_CONTAINER_VOLUME: 'standalone_compiler' # volume name = folderName_volumeName
      GRPC_PORT: 9092

      # Push notifications
      ENABLE_PUSH_NOTIFICATION: 'true'

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - compiler
    volumes:
      - ../prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - ../grafana_conf/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000

volumes:
  compiler:
    driver: local
